# Generated by Django 3.2.3 on 2021-05-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210521_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
