# Generated by Django 3.2.3 on 2021-05-21 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210521_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='guide',
        ),
        migrations.AddField(
            model_name='guide',
            name='tours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide', to='main.tour'),
        ),
    ]
