# Generated by Django 3.2.3 on 2021-05-21 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210521_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='tours',
        ),
        migrations.AddField(
            model_name='tour',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='main.guide'),
        ),
    ]
