# Generated by Django 3.2.3 on 2021-05-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='type',
        ),
    ]
