# Generated by Django 3.2.3 on 2021-05-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_rating_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='rating',
        ),
    ]
