# Generated by Django 3.2.3 on 2021-05-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_tour_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='view',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
