# Generated by Django 3.2.3 on 2021-05-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_tour_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
