# Generated by Django 3.2.3 on 2021-06-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210618_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='msg',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TextField(blank=True, verbose_name='Предполагаемое время'),
        ),
    ]
