# Generated by Django 3.2.3 on 2021-06-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210619_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Предполагаемое время'),
        ),
    ]
