# Generated by Django 3.2.3 on 2021-06-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
